server:
  port: 64202
spring:
  application:
    name: Cry-service
  banner:
    location: classpath:banner.txt
#  security:
#    basic:
#      enabled: false
key:
  path:
    public: public_key.pem
    private: private_key.pem
jwt:
  secret: wxkliBHdt6oJARUPaE8CYi1R8GtrW5MDcNkLLZL0SXc=
  ttl: 36000000