name: Deploy Vue3 to S3

on:
  push:
    branches:
      - task-vue  # 只在 push 到 main 分支時觸發

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # 啟用 OIDC 驗證
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./task-vue/my-vue-app  # 完整路徑到Vue項目目錄
        run: npm install

      - name: Build project
        working-directory: ./task-vue/my-vue-app  # 完整路徑到Vue項目目錄
        run: npm run build

# ... AWS credential setup ...
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}        # 這是 User 的憑證
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # 這是 User 的憑證
          role-to-assume: arn:aws:iam::533267147653:role/GitHubActionsS3Role-task-v2
          aws-region: ap-southeast-2

      - name: Deploy to S3
        run: aws s3 sync ./task-vue/my-vue-app/dist s3://fedoubt-prod-web-assets/task/v2 --delete